// apps/web/src/routes/_protected/_app/index.tsx
import { api } from "@hazel/backend/api"
import { useQuery } from "@tanstack/solid-query"
import { createFileRoute, Link, useNavigate } from "@tanstack/solid-router"
import { createEffect, For } from "solid-js"
import { Card } from "~/components/ui/card"
import { convexQuery } from "~/lib/convex-query"

export const Route = createFileRoute("/_protected/_app/")({
	component: App,
	// beforeLoad: async ({ context }) => {
	// 	await context.convex.awaitAuth()

	// 	const res = await context.convex.query(api.me.getOrganization, {})

	// 	if (res.directive === "redirect") {
	// 		throw redirect({
	// 			to: res.to,
	// 		})
	// 	}

	// 	if (res.directive === "success") {
	// 		throw redirect({
	// 			to: "/app",
	// 		})
	// 	}
	// },
})

function App() {
	const navigate = useNavigate()
	const serversQuery = useQuery(() => convexQuery(api.servers.getServersForUser, {}))

	createEffect(() => {
		if (serversQuery.data?.length === 0) {
			navigate({
				to: "/onboarding",
			})
		} else if (serversQuery.data && serversQuery.data.length > 0) {
			// Since one organization = one server, redirect directly to the app
			navigate({
				to: "/app/chat",
			})
		}
	})

	return (
		<main class="container mx-auto flex w-full py-14">
			<div class="flex flex-row gap-3">
				<For each={serversQuery.data}>
					{(server) => (
						<Link to="/app">
							<Card>
								<Card.Header>
									<Card.Title>{server.name}</Card.Title>
								</Card.Header>
							</Card>
						</Link>
					)}
				</For>
			</div>
		</main>
	)
}

// apps/web/src/routes/app/index.tsx
import { convexQuery } from "@convex-dev/react-query"
import { api } from "@hazel/backend/api"
import { useQuery } from "@tanstack/react-query"
import { createFileRoute, Navigate } from "@tanstack/react-router"

export const Route = createFileRoute("/app/")({
	component: RouteComponent,
})

function RouteComponent() {
	// Get current organization from session
	const organizationQuery = useQuery(convexQuery(api.me.getOrganization, {}))
	
	// Loading state
	if (organizationQuery.isLoading) {
		return (
			<div className="flex h-full items-center justify-center">
				<div className="h-8 w-8 animate-spin rounded-full border-primary border-b-2"></div>
			</div>
		)
	}
	
	// Handle redirect
	if (organizationQuery.data?.directive === "success") {
		const orgId = organizationQuery.data.data._id
		return <Navigate to="/app/$orgId" params={{ orgId }} />
	}
	
	// Handle redirect to onboarding or login
	if (organizationQuery.data?.directive === "redirect") {
		return <Navigate to={organizationQuery.data.to} />
	}
	
	// No organization found
	return (
		<div className="flex h-full items-center justify-center">
			<div className="text-center">
				<h2 className="mb-2 font-semibold text-xl">No Organization Found</h2>
				<p className="text-secondary">Please contact your administrator.</p>
			</div>
		</div>
	)
}
