// apps/legacy_app/src/main.tsx
import { RouterProvider, createRouter } from "@tanstack/solid-router"
import { render } from "solid-js/web"

import "solid-devtools"

import { routeTree } from "./routeTree.gen"
import "./styles.css"

import "./styles/code.css"
import "./styles/toast.css"
import { QueryClientProvider } from "@tanstack/solid-query"
import { Duration, Layer, LogLevel, Logger, ManagedRuntime } from "effect"
import { Toaster } from "./components/ui/toaster"
import { ApiClient } from "./lib/services/common/api-client"
import { NetworkMonitor } from "./lib/services/common/network-monitor"
import { QueryClient } from "./lib/services/common/query-client"
import type { LiveManagedRuntime } from "./lib/services/live-layer"
import { RuntimeProvider } from "./lib/services/runtime"

import { QueryClient as TanstackQueryClient } from "@tanstack/solid-query"
import { SolidQueryDevtools } from "@tanstack/solid-query-devtools"

const router = createRouter({
	routeTree,
	defaultPreload: "intent",
	scrollRestoration: true,
	defaultPreloadStaleTime: 0,
})

declare module "@tanstack/solid-router" {
	interface Register {
		router: typeof router
	}
}

const queryClient = new TanstackQueryClient({
	defaultOptions: {
		queries: {
			retry: false,
			retryDelay: 0,
			staleTime: Duration.toMillis("5 minutes"),
			gcTime: Duration.toMillis("12 hours"),
			refetchOnWindowFocus: false,
			refetchOnReconnect: "always",
		},
		mutations: {
			retry: false,
			retryDelay: 0,
		},
	},
})

const InnerProviders = () => {
	const runtime: LiveManagedRuntime = ManagedRuntime.make(
		Layer.mergeAll(
			NetworkMonitor.Default,
			ApiClient.Default,
			QueryClient.make(queryClient),
			Logger.minimumLogLevel(import.meta.env.DEV ? LogLevel.Debug : LogLevel.Info),
		).pipe(Layer.provide(Logger.pretty)),
	)

	return (
		<QueryClientProvider client={queryClient}>
			<SolidQueryDevtools initialIsOpen={false} />
			{/* <TanStackRouterDevtools position="bottom-right" /> */}

			<RuntimeProvider runtime={runtime}>
				<RouterProvider router={router} />
			</RuntimeProvider>
		</QueryClientProvider>
	)
}

function App() {
	return (
		<>
			<Toaster />
			<InnerProviders />
		</>
	)
}

const rootElement = document.getElementById("app")
if (rootElement) {
	render(() => <App />, rootElement)
}

// apps/react-shadcn/src/main.tsx
import { createRouter, RouterProvider } from "@tanstack/react-router"
import { StrictMode } from "react"
import ReactDOM from "react-dom/client"

// Import the generated route tree
import { routeTree } from "./routeTree.gen"

import "./styles/styles.css"

import { ConvexQueryClient } from "@convex-dev/react-query"
import { QueryClient, QueryClientProvider } from "@tanstack/react-query"
import { AuthKitProvider, useAuth } from "@workos-inc/authkit-react"
import { ConvexReactClient } from "convex/react"
import { ConvexProviderWithAuthKit } from "./components/convex-provider-with-authkit.tsx"
import { ThemeProvider } from "./components/theme-provider.tsx"
import reportWebVitals from "./reportWebVitals.ts"

const convex = new ConvexReactClient(import.meta.env.VITE_CONVEX_URL)

const convexQueryClient = new ConvexQueryClient(convex)

const queryClient: QueryClient = new QueryClient({
	defaultOptions: {
		queries: {
			queryKeyHashFn: convexQueryClient.hashFn(),
			queryFn: convexQueryClient.queryFn(),
		},
	},
})

convexQueryClient.connect(queryClient)

const router = createRouter({
	routeTree,
	context: { queryClient, convexClient: convex, convexQueryClient },
	defaultPreload: "intent",
	scrollRestoration: true,
	defaultStructuralSharing: true,
	defaultPreloadStaleTime: 0,
	Wrap: ({ children }) => (
		<ThemeProvider>
			<QueryClientProvider client={queryClient}>
				<AuthKitProvider
					clientId={import.meta.env.VITE_WORKOS_CLIENT_ID || "client_01HGZR2CV5G9VPBYK6XFA8YG17"}
					redirectUri={import.meta.env.VITE_WORKOS_REDIRECT_URI}
				>
					<ConvexProviderWithAuthKit client={convexQueryClient.convexClient} useAuth={useAuth}>
						{children}
					</ConvexProviderWithAuthKit>
				</AuthKitProvider>
			</QueryClientProvider>
		</ThemeProvider>
	),
})

declare module "@tanstack/react-router" {
	interface Register {
		router: typeof router
	}
}

const rootElement = document.getElementById("app")
if (rootElement && !rootElement.innerHTML) {
	const root = ReactDOM.createRoot(rootElement)
	root.render(
		<StrictMode>
			<RouterProvider router={router} />
		</StrictMode>,
	)
}

reportWebVitals()
